### ISSUE TITLE
노션 글의 깃허브 링크 오류

### ISSUE THREAD

**Issue by feel0321** [H-Wol/algorithmStudyTemplate#1]
### 버그 내용

![스크린샷 2023-06-13 오전 12 02 33](https://github.com/H-Wol/algorithmStudyTemplate/assets/50919342/7a8b678c-e857-4a93-a595-c34b23d97ece)

깃허브 액션으로 노션에 글이 추가됩니다
해당 깃헙 링크를 눌러보면 아래와 같은 화면이 나옵니다

![스크린샷 2023-06-13 오전 12 03 16](https://github.com/H-Wol/algorithmStudyTemplate/assets/50919342/601e5b65-b8ef-47eb-bbae-4f190cfa92e5)

`쿼트가 들어간거` 하고 `url 디코딩` 관련 문제가 아닌가 싶습니다

**Comment by H-Wol** [comment]
수정하였으니 문제 풀이후 확인바랍니다

**Comment by feel0321** [comment]
@H-Wol 해결된것을 확인했습니다. 감사합니다
이슈 닫을게요
