### ISSUE TITLE
solved.ac api 403 오류로 인한 auto_notion_post.py 실패

### ISSUE THREAD

**Issue by feel0321** [H-Wol/algorithmStudyTemplate#3]
solved.ac api로 문제에 대한 정보를 읽어오는데
solved.ac api 403 오류가 발생

원인
- [가장 근접한 CORS 오류](https://github.com/solvedac/unofficial-documentation/issues/51)
- github action으로 보내는 요청의 header 이상

**Comment by feel0321** [comment]
[http-request-action](https://github.com/marketplace/actions/http-request-action)을 통해 github action의 header를 수정할 수 있을지도 모른다

**Comment by H-Wol** [comment]
github action에서 solved ac로 보내는 요청이 막힌듯하여 관련 기능은 주석처리 하였습니다.
이후 노션에 등록되는 게시글은 문제 난이도, 문제 태그, 문제 이름이 빈칸으로 들어갈 예정입니다.
